In [1]:
import numpy as np

stock1 = np.array([
[100,105,98],
[102,108,99],
[101,107,97],
[103,109,100],
[104,110,101]
])

stock2 = np.array([
[98,104,96],
[100,106,97],
[99,105,95],
[101,107,98],
[102,108,99]
])

sum_matrix = stock1 + stock2
diff_matrix = stock1 - stock2

print("Element-wise Sum:\n", sum_matrix)
print("Element-wise Difference:\n", diff_matrix)

Element-wise Sum:
 [[198 209 194]
 [202 214 196]
 [200 212 192]
 [204 216 198]
 [206 218 200]]
Element-wise Difference:
 [[2 1 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
